# -*- coding: utf-8 -*-
"""Tomáš Ženíšek-BULLS AND COWS.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/11LXpN8j_S5bhB9y9AMThc6vT4zIDNb9D
"""

import random

def hadane_cislo():
  prvni_cis = random.randint(1, 9)
  druha_cis = random.randint(0, 9)
  while druha_cis == prvni_cis:
    druha_cis = random.randint(0, 9)

  treti_cis = random.randint(0, 9)
  while treti_cis == prvni_cis or treti_cis == druha_cis:
      treti_cis = random.randint(0, 9)

  ctvrta_cis = random.randint(0, 9)
  while ctvrta_cis == prvni_cis or ctvrta_cis == druha_cis or ctvrta_cis == treti_cis:
      ctvrta_cis = random.randint(0, 9)

  return f"{prvni_cis}{druha_cis}{treti_cis}{ctvrta_cis}"

def bulls_and_cows(secret, guess):
    bulls = sum(1 for i in range(4) if secret[i] == guess[i])
    cows = sum(1 for x in guess if x in secret) - bulls
    return bulls, cows

gen_cislo = hadane_cislo()

print ("dobrý den")
print("-" * 30)
print ("budeme hrát hru s názvem bulls and cows, bude to 4místné číslo,které nezačíná nulou a každá číslice je unikátní")
print("START")


while True:
    pokus = input("Tvůj tip: ")

    if len(pokus) != 4 or not pokus.isdigit() or len(set(pokus)) != 4 or pokus[0] == "0":
        print("Chyba: napiš číslo ve správném formátu(4 unikátní číslice a nezačíná 0).")
        continue

    bulls, cows = bulls_and_cows(gen_cislo, pokus)
    print(f"Bulls: {bulls}, Cows: {cows}")

    if bulls == 4:
        print("AHHHHH EZ WIN!")
        break
    else:
        print("Nejde nic, zkus to znova.")